### ISSUE TITLE
 pandas.errors.EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by csittz** [nf-core/circrna#162]
### Description of feature

Hi i believe the reason for this error is due to there is no circrna found in my samples (file size 0 in the result/intersect folder). There was no common circrna found in the two algorithms
 --tool 'ciriquant','circexplorer2' 
  --tool_filter 2 

However, the pipeline just stop and exit. Would it be possible to get the pipeline to continue to execute by skipping samples without circrna? thank you.

Error message 
```
ERROR ~ Error executing process > NFCORE_CIRCRNA:CIRCRNA:CIRCRNA_DISCOVERY:ANNOTATION:ANNOTATE (sampleX:merged)

Caused by:
  Process NFCORE_CIRCRNA:CIRCRNA:CIRCRNA_DISCOVERY:ANNOTATION:ANNOTATE (sampleX:merged) terminated with an error exit status (1)


Command executed:

  annotation.py --input sampleX.intersect.bed --exon_boundary 200 --output_bed sampleX.merged.annotated.bed --output_gtf sampleX.merged.annotated.gtf

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CIRCRNA:CIRCRNA:CIRCRNA_DISCOVERY:ANNOTATION:ANNOTATE":
      python: $(python --version | sed 's/Python //g')
      pandas: $(python -c "import pandas; print(pandas.__version__)")
      numpy: $(python -c "import numpy; print(numpy.__version__)")
  END_VERSIONS

Command exit status:
 1

Command output:
  (empty)

Command error:
  INFO:    Could not find any nv files on this host!
  Traceback (most recent call last):
    File "circrna/bin/annotation.py", line 33, in <module>
      df = pd.read_csv(args.input, sep="\t", header=None, usecols=columns.keys())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
      return func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
      return func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
      return _read(filepath_or_buffer, kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
      parser = TextFileReader(filepath_or_buffer, **kwds)
File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
  pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by nictru** [comment]
Hey, please follow #159 for this
